---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Values.Namespace }}
  name: tgzeposter
spec:
  concurrencyPolicy: Forbid
  suspend: false
  schedule: "{{ .Values.CronSchedule }}"
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 6
  jobTemplate:
    metadata:
      name: tgzeposter
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: tgzeposter
            imagePullPolicy: Always
            image: {{ .Values.ImageName }}:{{ .Values.ImageTag }}
            envFrom:
              - configMapRef:
                  name: tgzeposter
