---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tgposter
  labels:
    app: tgposter
spec:
  selector:
    matchLabels:
      app: tgposter
  template:
    metadata:
      name: tgposter
      labels:
        app: tgposter
    spec:
      containers:
      - name: tgposter
        imagePullPolicy: IfNotPresent
        image: "{{ $.Values.ImageNameTgPoster }}:{{ $.Values.ImageTagTgPoster }}"
        envFrom:
          - configMapRef:
              name: tgposter

