---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: tgposter
  namespace: {{ $.Release.Namespace }}
  labels:
    app: tgposter

spec:

  selector:
    matchLabels:
      app: tgposter

  template:
    metadata:
      name: tgposter
      labels:
        app: tgposter
    spec:

      containers:

        - name: tgposter
          image: "{{ $.Values.ImageNameGithubTgPoster }}:{{ $.Values.ImageTagGithubTgPoster }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: tgposter

