---

DEBUG: false

YamlConfigPath: tgposter.yaml

Interval: 11m

KvToken: ""
KvAccountId: ""
KvNamespaceId: ""

TgToken: ""
TgChatId: ""

ImageNameTgPoster: ghcr.io/shoce/tgposter
ImageTagTgPoster: ""

